### ISSUE TITLE
Huge amounts of Baby Pig Zombies in Nether.

### ISSUE THREAD

**Issue by JoelZBub** [Furgl/BabyMobs#1]
Running 1.8.9-1.4 

The number of baby zombie pigs reaches huge numbers. I've had to execute /kill @e in order to clear out as many as 1200 baby pig zombies.  This is running on a dedicated server. I have spawn rates in config for baby pig zombies set at default 25%.

Ubuntu Linux server
Java 8
Forge 11.15.1.1902

**Comment by Furgl** [comment]
Thank you for the post,
This is probably caused by Baby Zombie Pigs not despawning properly; I posted a hotfix where this is fixed:

[BabyMobs-1.8.9-1.4-Hotfix.zip](https://github.com/Furgl/BabyMobs/files/333921/BabyMobs-1.8.9-1.4-Hotfix.zip)

**Comment by JoelZBub** [comment]
Thank you so much for a fix!
Would it be too much to ask to have a patched version uploaded to CurseForge so that this could be included in modpack updates on the Curse launcher without hassle? 
If not, no worries.
Again... thanks. :)

**Comment by Furgl** [comment]
Curse was having some problems approving the file, but it's up there now.
Happy to help!
