### ISSUE TITLE
Server crash with Baby Iron Golem

### ISSUE THREAD

**Issue by NathanHawks** [Furgl/BabyMobs#14]
I'm afraid our server community doesn't have the personal bandwidth to troubleshoot; but we wanted to pass these crash logs along.

[crash-2017-09-08_20.46.30-server.txt](https://github.com/Furgl/BabyMobs/files/1289933/crash-2017-09-08_20.46.30-server.txt)
[crash-2017-09-08_20.40.18-server.txt](https://github.com/Furgl/BabyMobs/files/1289932/crash-2017-09-08_20.40.18-server.txt)

**Comment by Furgl** [comment]
Unfortunately, 1.7.10 is no longer supported. I'm afraid there's nothing I can do to fix this.
