### ISSUE TITLE
[Feature] Morph Mod compatible 

### ISSUE THREAD

**Issue by JoeSGT** [Furgl/BabyMobs#19]
Hello can you some how add Morph mod compatible so we can have the ability to morph into the baby mobs i personally think it's cool to morph into them and be just like them please consider this here is the mod on what i am talking about, currently we cannot morph into them  
https://minecraft.curseforge.com/projects/morph

**Comment by Furgl** [comment]
Hello. Morph is only for 1.7.10, which is very outdated now. I do not support 1.7.10, so even if I could fix this compatibility issue, I will not for that version.

**Comment by JoeSGT** [comment]
https://minecraft.curseforge.com/projects/morph/files
no it's not Stuck at 1.7.10 it's been updated to 1.12.2

**Comment by JoeSGT** [comment]
If you click on the link i gave you above you can see that's not only on 1.7.10

**Comment by Furgl** [comment]
I see that, I was looking at iChun's blog, which is apparently very outdated. I will look into how his mod works.

**Comment by JoeSGT** [comment]
here his source to morph mod
https://github.com/iChun/Morph/tree/1.12.2

**Comment by Furgl** [comment]
Baby mobs are already compatible with Morph; enable Child Morphs in the Morph config.
