### ISSUE TITLE
Immortal Cat

### ISSUE THREAD

**Issue by frakier** [Furgl/BabyMobs#25]
FriendlyFire-1.12.2-1.5.9
BabyMobs-1.12-1.5.5
Forge 14.23.5.2807

The BabyMobs version of the Cat that follows around the Minecraft Witch [not the Ender Zoo Cat] has the label "tamed" and you cannot attack it [not sure if the label matters but so far the only mob I have found that has a issue]. One of my players thought it was a joke until it got serious; He died.

Will be sharing this with FriendlyFire as well.

**Comment by Furgl** [comment]
My guess is you have protectBabies enabled in the FriendlyFire config. Disable that or sneak while attacking the baby ocelot.

**Comment by frakier** [comment]
Thanks will try and report back

**Comment by frakier** [comment]
That was it. Thanks again.
