### ISSUE TITLE
Error Ticking Entity (Server Crash) (Baby Wither)

### ISSUE THREAD

**Issue by Renari** [Furgl/BabyMobs#6]
https://gist.github.com/Renari/3a220dbdfe9123face54e6007f0920b0

**Comment by Furgl** [comment]
I'm not sure how this crash can happen without outside interference of another mod, but this should fix it: 
[BabyMobs-1.10.2-1.5.4.jar.zip](https://github.com/Furgl/BabyMobs/files/709608/BabyMobs-1.10.2-1.5.4.jar.zip)
